M48
; DRILL file {KiCad (6.0.0-0)} date Saturday, 15 January 2022 at 15:56:37
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-15T15:56:37+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.1654Y-1.5748
X2.1654Y-4.3307
X5.1181Y-1.5748
X5.1181Y-4.3307
T0
M30
